/**
 * RumahSubsidi.id - Configuration
 * Auto-generated from env.yaml
 * DO NOT EDIT THIS FILE DIRECTLY - Edit env.yaml instead and run: node generate-config.js
 */

const APP_CONFIG = {
  "app": {
    "name": "RumahSubsidi.id",
    "version": "1.0.0",
    "environment": "development"
  },
  "server": {
    "web": {
      "port": 8000,
      "host": "0.0.0.0",
      "baseURL": "http://localhost:8000"
    },
    "proxy": {
      "port": 8001,
      "host": "0.0.0.0",
      "baseURL": "http://localhost:8001"
    }
  },
  "api": {
    "sikumbang": {
      "baseURL": "https://sikumbang.tapera.go.id",
      "endpoints": {
        "search": "/ajax/lokasi/search",
        "detail": "/lokasi-perumahan",
        "provinsi": "/ajax/wilayah/get-provinsi",
        "kabupaten": "/ajax/wilayah/get-kabupaten",
        "kecamatan": "/ajax/wilayah/get-kecamatan"
      },
      "timeout": 30000
    },
    "nominatim": {
      "baseURL": "https://nominatim.openstreetmap.org",
      "userAgent": "RumahSubsidi.id/1.0"
    }
  },
  "proxy": {
    "endpoints": {
      "nik": "/api/cek-subsidi",
      "detail": "/api/detail-perumahan"
    }
  },
  "cache": {
    "ttl": 300000,
    "geolocation": {
      "ttl": 86400000
    }
  },
  "geolocation": {
    "enabled": true,
    "timeout": 5000,
    "maximumAge": 0,
    "enableHighAccuracy": false
  },
  "defaults": {
    "limit": 100,
    "homepageLimit": 18,
    "cacheStrategy": "reload"
  }
};

// Freeze config to prevent modifications
Object.freeze(APP_CONFIG);

// Helper function to get nested config values
function getConfig(path) {
  return path.split('.').reduce((obj, key) => obj?.[key], APP_CONFIG);
}

// Export for Node.js (if running in Node environment)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { APP_CONFIG, getConfig };
}
